-- Характеристики товаров для фильтров (тип продукта, объём, тип волос, тип кожи).
-- Безопасная миграция: только ДОБАВЛЯЕТ колонку и заполняет её. Товары, фото, цены, названия
-- и артикулы не удаляются и не меняются. Можно запускать повторно.
-- Запустить в Supabase → SQL Editor.
alter table products add column if not exists attributes jsonb not null default '{}'::jsonb;

update products set attributes = '{"productType":"Гель для умывания","volume":"150 мл","skinType":["dry","oily","combination","normal","sensitive"]}'::jsonb where sku = 'DEMO-FF-01';
update products set attributes = '{"productType":"Мицеллярная вода","volume":"250 мл","skinType":["dry","oily","combination","normal","sensitive"]}'::jsonb where sku = 'DEMO-FF-02';
update products set attributes = '{"productType":"Пенка для умывания","volume":"150 мл","skinType":["sensitive","normal"]}'::jsonb where sku = 'DEMO-FF-03';
update products set attributes = '{"productType":"Крем","volume":"50 мл","skinType":["dry"]}'::jsonb where sku = 'DEMO-FC-01';
update products set attributes = '{"productType":"Ночной крем","volume":"50 мл","skinType":["normal","dry"]}'::jsonb where sku = 'DEMO-FC-02';
update products set attributes = '{"productType":"Крем-гель","volume":"50 мл","skinType":["oily","combination"]}'::jsonb where sku = 'DEMO-FC-03';
update products set attributes = '{"productType":"Крем для рук","volume":"75 мл"}'::jsonb where sku = 'DEMO-FC-04';
update products set attributes = '{"productType":"Сыворотка","volume":"30 мл","skinType":["normal","dry","combination"]}'::jsonb where sku = 'DEMO-FS-01';
update products set attributes = '{"productType":"Сыворотка","volume":"30 мл","skinType":["dry","sensitive"]}'::jsonb where sku = 'DEMO-FS-02';
update products set attributes = '{"productType":"Сыворотка","volume":"30 мл","skinType":["oily","combination"]}'::jsonb where sku = 'DEMO-FS-03';
update products set attributes = '{"productType":"Сыворотка","volume":"30 мл","skinType":["normal","dry"]}'::jsonb where sku = 'DEMO-FS-04';
update products set attributes = '{"productType":"Тканевая маска","volume":"5 шт","skinType":["dry","oily","combination","normal","sensitive"]}'::jsonb where sku = 'DEMO-FM-01';
update products set attributes = '{"productType":"Глиняная маска","volume":"100 мл","skinType":["oily","combination"]}'::jsonb where sku = 'DEMO-FM-02';
update products set attributes = '{"productType":"Солнцезащитный крем","volume":"50 мл","skinType":["dry","oily","combination","normal","sensitive"]}'::jsonb where sku = 'DEMO-SP-01';
update products set attributes = '{"productType":"Солнцезащитный флюид","volume":"40 мл","skinType":["oily","combination"]}'::jsonb where sku = 'DEMO-SP-02';
update products set attributes = '{"productType":"Солнцезащитный спрей","volume":"150 мл"}'::jsonb where sku = 'DEMO-SP-03';
update products set attributes = '{"productType":"Мицеллярная вода","volume":"250 мл","skinType":["sensitive"]}'::jsonb where sku = 'DEMO-AP-01';
update products set attributes = '{"productType":"Крем","volume":"50 мл","skinType":["sensitive","dry"]}'::jsonb where sku = 'DEMO-AP-02';
update products set attributes = '{"productType":"Гель против акне","volume":"30 мл","skinType":["oily","combination"]}'::jsonb where sku = 'DEMO-AP-03';
update products set attributes = '{"productType":"Лосьон для тела","volume":"250 мл"}'::jsonb where sku = 'DEMO-BD-01';
update products set attributes = '{"productType":"Скраб для тела","volume":"200 г"}'::jsonb where sku = 'DEMO-BD-02';
update products set attributes = '{"productType":"Масло для тела","volume":"100 мл"}'::jsonb where sku = 'DEMO-BD-03';
update products set attributes = '{"productType":"Роллер для лица"}'::jsonb where sku = 'DEMO-MS-01';
update products set attributes = '{"productType":"Гуаша"}'::jsonb where sku = 'DEMO-MS-02';
update products set attributes = '{"productType":"Массажёр для тела"}'::jsonb where sku = 'DEMO-MS-03';
update products set attributes = '{"productType":"Шампунь","volume":"250 мл","hairType":["dry","damaged"]}'::jsonb where sku = 'DEMO-HS-01';
update products set attributes = '{"productType":"Шампунь","volume":"250 мл","hairType":["dry"]}'::jsonb where sku = 'DEMO-HS-02';
update products set attributes = '{"productType":"Шампунь","volume":"250 мл","hairType":["oily"]}'::jsonb where sku = 'DEMO-HS-03';
update products set attributes = '{"productType":"Шампунь","volume":"400 мл","hairType":["oily"]}'::jsonb where sku = 'DEMO-HS-04';
update products set attributes = '{"productType":"Кондиционер","volume":"250 мл","hairType":["dry","damaged"]}'::jsonb where sku = 'DEMO-HC-01';
update products set attributes = '{"productType":"Кондиционер","volume":"250 мл","hairType":["oily","normal"]}'::jsonb where sku = 'DEMO-HC-02';
update products set attributes = '{"productType":"Кондиционер","volume":"200 мл","hairType":["colored","damaged"]}'::jsonb where sku = 'DEMO-HC-03';
update products set attributes = '{"productType":"Маска для волос","volume":"200 мл","hairType":["dry","damaged"]}'::jsonb where sku = 'DEMO-HR-02';
update products set attributes = '{"productType":"Маска для волос","volume":"150 мл","hairType":["damaged","dry"]}'::jsonb where sku = 'DEMO-HK-01';
update products set attributes = '{"productType":"Маска для волос","volume":"200 мл","hairType":["oily"]}'::jsonb where sku = 'DEMO-HK-02';
update products set attributes = '{"productType":"Маска для волос","volume":"200 мл","hairType":["colored"]}'::jsonb where sku = 'DEMO-HK-03';
update products set attributes = '{"productType":"Сыворотка для волос","volume":"50 мл","hairType":["dry","damaged"]}'::jsonb where sku = 'DEMO-HR-03';
update products set attributes = '{"productType":"Масло для волос","volume":"100 мл","hairType":["normal","dry"]}'::jsonb where sku = 'DEMO-HR-04';
update products set attributes = '{"productType":"Помада","volume":"4 г"}'::jsonb where sku = 'DEMO-MK-01';
update products set attributes = '{"productType":"Тушь","volume":"10 мл"}'::jsonb where sku = 'DEMO-MK-02';
update products set attributes = '{"productType":"Палетка теней","volume":"12 цветов"}'::jsonb where sku = 'DEMO-MK-03';
update products set attributes = '{"productType":"Парфюмерная вода","volume":"50 мл"}'::jsonb where sku = 'DEMO-PF-01';
update products set attributes = '{"productType":"Туалетная вода","volume":"50 мл"}'::jsonb where sku = 'DEMO-PF-02';
update products set attributes = '{"productType":"Набор миниатюр","volume":"3 × 10 мл"}'::jsonb where sku = 'DEMO-PF-03';
update products set attributes = '{"productType":"Прокладки","volume":"40 шт"}'::jsonb where sku = 'DEMO-GG-01';
update products set attributes = '{"productType":"Гель для интимной гигиены","volume":"200 мл"}'::jsonb where sku = 'DEMO-GG-02';
update products set attributes = '{"productType":"Тампоны","volume":"16 шт"}'::jsonb where sku = 'DEMO-GG-03';
update products set attributes = '{"productType":"Комплект белья"}'::jsonb where sku = 'DEMO-UW-01';
update products set attributes = '{"productType":"Трусики","volume":"3 шт"}'::jsonb where sku = 'DEMO-UW-02';
update products set attributes = '{"productType":"Бюстгальтер"}'::jsonb where sku = 'DEMO-UW-03';
update products set attributes = '{"productType":"Жидкое мыло","volume":"500 мл"}'::jsonb where sku = 'DEMO-SO-01';
update products set attributes = '{"productType":"Гель для душа","volume":"400 мл"}'::jsonb where sku = 'DEMO-SO-02';
update products set attributes = '{"productType":"Мыло","volume":"100 г"}'::jsonb where sku = 'DEMO-SO-03';
update products set attributes = '{"productType":"Свеча"}'::jsonb where sku = 'DEMO-HM-01';
update products set attributes = '{"productType":"Диффузор","volume":"100 мл"}'::jsonb where sku = 'DEMO-HM-02';
update products set attributes = '{"productType":"Спрей для текстиля","volume":"250 мл"}'::jsonb where sku = 'DEMO-HM-03';
update products set attributes = '{"productType":"Детский шампунь","volume":"250 мл"}'::jsonb where sku = 'DEMO-KD-01';
update products set attributes = '{"productType":"Детский крем","volume":"100 мл"}'::jsonb where sku = 'DEMO-KD-02';
update products set attributes = '{"productType":"Детская зубная паста","volume":"50 мл"}'::jsonb where sku = 'DEMO-KD-03';
update products set attributes = '{"productType":"Расчёска"}'::jsonb where sku = 'DEMO-AC-01';
update products set attributes = '{"productType":"Резинки для волос","volume":"10 шт"}'::jsonb where sku = 'DEMO-AC-02';
update products set attributes = '{"productType":"Косметичка"}'::jsonb where sku = 'DEMO-AC-03';
update products set attributes = '{"productType":"Шоппер"}'::jsonb where sku = 'DEMO-MR-01';
update products set attributes = '{"productType":"Худи"}'::jsonb where sku = 'DEMO-MR-02';
update products set attributes = '{"productType":"Кружка","volume":"350 мл"}'::jsonb where sku = 'DEMO-MR-03';
update products set attributes = '{"productType":"Подарочный набор","volume":"3 шт"}'::jsonb where sku = 'DEMO-GF-01';
update products set attributes = '{"productType":"Подарочный набор","volume":"3 шт"}'::jsonb where sku = 'DEMO-GF-02';
update products set attributes = '{"productType":"Сертификат"}'::jsonb where sku = 'DEMO-GF-03';
