-- Демо-данные для списков подразделов внутри «Ухода за кожей» (Уход для лица → Умывание, Сыворотки…).
-- ТОЛЬКО ДОБАВЛЯЕТ: дописывает теги/старые цены/«Хит» в характеристики существующих товаров и
-- добавляет новые демо-товары для пустых подразделов. Ничего не удаляет и не перезаписывает.
-- Запустить в Supabase → SQL Editor (можно повторно). Сначала должна быть выполнена product_attributes.sql.

update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cleansing"]'::jsonb) where sku = 'DEMO-FF-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cleansing","makeup-removal"]'::jsonb, 'oldPrice', round(price * 1.5 / 10) * 10) where sku = 'DEMO-FF-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cleansing"]'::jsonb, 'oldPrice', round(price * 1.7 / 10) * 10, 'hit', true) where sku = 'DEMO-FF-03';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cream"]'::jsonb, 'oldPrice', round(price * 1.8 / 10) * 10, 'hit', true) where sku = 'DEMO-FC-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cream","antiage"]'::jsonb, 'oldPrice', round(price * 1.6 / 10) * 10) where sku = 'DEMO-FC-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cream","problem"]'::jsonb) where sku = 'DEMO-FC-03';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["body-hands"]'::jsonb, 'oldPrice', round(price * 1.4 / 10) * 10) where sku = 'DEMO-FC-04';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["serum","antiage"]'::jsonb, 'oldPrice', round(price * 2.1 / 10) * 10, 'hit', true) where sku = 'DEMO-FS-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["serum"]'::jsonb, 'oldPrice', round(price * 1.7 / 10) * 10) where sku = 'DEMO-FS-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["serum","problem"]'::jsonb, 'oldPrice', round(price * 2.4 / 10) * 10, 'hit', true) where sku = 'DEMO-FS-03';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["serum","antiage"]'::jsonb, 'oldPrice', round(price * 1.9 / 10) * 10) where sku = 'DEMO-FS-04';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["mask"]'::jsonb, 'oldPrice', round(price * 1.5 / 10) * 10, 'hit', true) where sku = 'DEMO-FM-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["mask","problem"]'::jsonb) where sku = 'DEMO-FM-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cleansing","makeup-removal"]'::jsonb) where sku = 'DEMO-AP-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["cream"]'::jsonb, 'oldPrice', round(price * 1.6 / 10) * 10) where sku = 'DEMO-AP-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["problem"]'::jsonb, 'oldPrice', round(price * 1.8 / 10) * 10, 'hit', true) where sku = 'DEMO-AP-03';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["body-cream"]'::jsonb, 'oldPrice', round(price * 1.5 / 10) * 10) where sku = 'DEMO-BD-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["body-scrub"]'::jsonb, 'oldPrice', round(price * 1.7 / 10) * 10, 'hit', true) where sku = 'DEMO-BD-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["body-oil"]'::jsonb, 'oldPrice', round(price * 1.6 / 10) * 10) where sku = 'DEMO-BD-03';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["spf-face"]'::jsonb, 'oldPrice', round(price * 1.8 / 10) * 10, 'hit', true) where sku = 'DEMO-SP-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["spf-face","spf-spray"]'::jsonb, 'oldPrice', round(price * 1.5 / 10) * 10) where sku = 'DEMO-SP-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["spf-body","spf-spray"]'::jsonb, 'oldPrice', round(price * 1.6 / 10) * 10) where sku = 'DEMO-SP-03';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["massage-face"]'::jsonb, 'oldPrice', round(price * 1.7 / 10) * 10, 'hit', true) where sku = 'DEMO-MS-01';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["massage-face"]'::jsonb, 'oldPrice', round(price * 1.5 / 10) * 10) where sku = 'DEMO-MS-02';
update products set attributes = coalesce(attributes, '{}'::jsonb) || jsonb_build_object('tags', '["massage-body"]'::jsonb, 'oldPrice', round(price * 1.8 / 10) * 10) where sku = 'DEMO-MS-03';

insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-MN-01', 'Патчи с микроиглами для морщин', 'Seoul Skin', 'Сыворотки', 1290, 'Микроиглы из гиалуроновой кислоты для разглаживания морщин.', 'Гиалуроновая кислота, 10 пар', 'Зрелая кожа', true, '/demo/photos/9PnU-U7V6YE.jpg', '{"productType":"Средство с микроиглами","volume":"10 пар","tags":["microneedle","antiage"],"skinType":["normal","dry"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(1290 * 2.3 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-MN-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-MN-02', 'Микроигольные патчи от воспалений', 'Seoul Skin', 'Сыворотки', 890, 'Точечно убирают воспаления за ночь.', 'Салициловая кислота, 12 патчей', 'Проблемная кожа', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Средство с микроиглами","volume":"12 шт","tags":["microneedle","problem"],"skinType":["oily","combination"]}'::jsonb || jsonb_build_object('oldPrice', round(890 * 1.9 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-MN-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PD-01', 'Сыворотка с ПДРН «Salmon»', 'Seoul Skin', 'Сыворотки', 1850, 'Восстанавливающая сыворотка с ПДРН.', 'ПДРН 2%, пантенол', 'Уставшая кожа', true, '/demo/photos/pd4rqJMd51Q.jpg', '{"productType":"Сыворотка с ПДРН","volume":"30 мл","tags":["pdrn","serum","antiage"],"skinType":["normal","dry","sensitive"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(1850 * 2.2 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PD-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PD-02', 'Ампула с ПДРН и центеллой', 'Dermalux', 'Сыворотки', 1590, 'Ампула для восстановления кожи после процедур.', 'ПДРН, центелла', 'Чувствительная кожа', true, '/demo/photos/LeWrouH2qto.jpg', '{"productType":"Сыворотка с ПДРН","volume":"30 мл","tags":["pdrn","serum"],"skinType":["sensitive","dry"]}'::jsonb || jsonb_build_object('oldPrice', round(1590 * 1.8 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PD-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-TN-01', 'Тонер увлажняющий с гиалуроновой кислотой', 'Seoul Skin', 'Тоники', 780, 'Увлажняет и готовит кожу к уходу.', 'Гиалуроновая кислота, алоэ', 'Все типы кожи', true, '/demo/photos/20h-C0vaNBA.jpg', '{"productType":"Тонер","volume":"200 мл","tags":["toner"],"skinType":["dry","oily","combination","normal","sensitive"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(780 * 1.7 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-TN-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-TN-02', 'Тонер-баланс для жирной кожи', 'Dermalux', 'Тоники', 720, 'Регулирует жирность, сужает поры.', 'Ниацинамид, цинк', 'Жирная и комбинированная кожа', true, '/demo/photos/9PnU-U7V6YE.jpg', '{"productType":"Тонер","volume":"200 мл","tags":["toner","problem"],"skinType":["oily","combination"]}'::jsonb || jsonb_build_object('oldPrice', round(720 * 1.5 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-TN-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-TN-03', 'Лосьон успокаивающий с центеллой', 'Seoul Skin', 'Тоники', 850, 'Успокаивает раздражения и покраснения.', 'Центелла, пантенол', 'Чувствительная кожа', true, '/demo/photos/20h-C0vaNBA.jpg', '{"productType":"Лосьон","volume":"150 мл","tags":["toner"],"skinType":["sensitive","dry"]}'::jsonb || jsonb_build_object('oldPrice', round(850 * 1.6 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-TN-03');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-SC-01', 'Пилинг-скатка с AHA-кислотами', 'Dermalux', 'Уход за лицом', 690, 'Мягко отшелушивает и выравнивает тон.', 'AHA-кислоты, папайя', 'Тусклая кожа', true, '/demo/photos/omY18KP7_Cw.jpg', '{"productType":"Пилинг","volume":"100 мл","tags":["scrub"],"skinType":["normal","combination","oily"]}'::jsonb || jsonb_build_object('oldPrice', round(690 * 1.6 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-SC-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-SC-02', 'Скраб для лица кофейный', 'Silk Lab', 'Уход за лицом', 540, 'Деликатно очищает поры.', 'Кофе, масло ши', 'Нормальная кожа', true, '/demo/photos/omY18KP7_Cw.jpg', '{"productType":"Скраб","volume":"75 мл","tags":["scrub"],"skinType":["normal","dry"]}'::jsonb || jsonb_build_object('oldPrice', round(540 * 1.4 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-SC-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PA-01', 'Тонер-пэды с кислотами, 60 шт', 'Seoul Skin', 'Уход за лицом', 1190, 'Отшелушивающие пэды для домашнего ухода.', 'PHA/AHA, 60 пэдов', 'Тусклая кожа', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Пэды","volume":"60 шт","tags":["pad"],"skinType":["normal","oily","combination"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(1190 * 2 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PA-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PA-02', 'Успокаивающие пэды с центеллой', 'Seoul Skin', 'Уход за лицом', 990, 'Снимают покраснения, увлажняют.', 'Центелла, 70 пэдов', 'Чувствительная кожа', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Пэды","volume":"70 шт","tags":["pad"],"skinType":["sensitive","dry"]}'::jsonb || jsonb_build_object('oldPrice', round(990 * 1.7 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PA-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-EY-01', 'Крем для кожи вокруг глаз с пептидами', 'Dermalux', 'Уход за глазами', 1150, 'Уменьшает тёмные круги и мелкие морщины.', 'Пептиды, кофеин', 'Зрелая кожа', true, '/demo/photos/lpFTFW9BZSU.jpg', '{"productType":"Крем для глаз","volume":"20 мл","tags":["eye","antiage"],"skinType":["normal","dry"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(1150 * 2 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-EY-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-EY-02', 'Гель для век охлаждающий', 'Glow Co', 'Уход за глазами', 780, 'Снимает отёчность и усталость.', 'Алоэ, огуречный экстракт', 'Уставшие глаза', true, '/demo/photos/XanILp6v_Eg.jpg', '{"productType":"Гель для век","volume":"15 мл","tags":["eye"],"skinType":["dry","oily","combination","normal","sensitive"]}'::jsonb || jsonb_build_object('oldPrice', round(780 * 1.5 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-EY-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-LP-01', 'Бальзам для губ «Вишня»', 'Silk Lab', 'Уход за лицом', 290, 'Питает и защищает губы.', 'Масло ши, пчелиный воск', 'Сухие губы', true, '/demo/photos/NnsqpLjiA94.jpg', '{"productType":"Бальзам для губ","volume":"10 г","tags":["lips"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(290 * 1.4 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-LP-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-LP-02', 'Маска для губ ночная', 'Seoul Skin', 'Уход за лицом', 520, 'Интенсивное питание губ за ночь.', 'Керамиды, масло ши', 'Потрескавшиеся губы', true, '/demo/photos/NnsqpLjiA94.jpg', '{"productType":"Маска для губ","volume":"8 г","tags":["lips"]}'::jsonb || jsonb_build_object('oldPrice', round(520 * 1.6 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-LP-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PT-01', 'Гидрогелевые патчи под глаза, 60 шт', 'Seoul Skin', 'Уход за глазами', 950, 'Охлаждают и уменьшают отёки.', 'Коллаген, золото, 60 шт', 'Уставшая кожа', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Патчи","volume":"60 шт","tags":["patch","eye"],"skinType":["dry","oily","combination","normal","sensitive"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(950 * 2.1 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PT-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PT-02', 'Патчи от акне «Точка»', 'Dermalux', 'Уход за лицом', 420, 'Прозрачные патчи на воспаления.', 'Гидроколлоид, 36 шт', 'Проблемная кожа', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Патчи","volume":"36 шт","tags":["patch","problem"],"skinType":["oily","combination"]}'::jsonb || jsonb_build_object('oldPrice', round(420 * 1.5 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PT-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-PT-03', 'Патчи для носогубных складок', 'Seoul Skin', 'Уход за лицом', 880, 'Разглаживающие патчи с гиалуроновой кислотой.', 'Гиалуроновая кислота, 10 пар', 'Зрелая кожа', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Патчи","volume":"10 пар","tags":["patch","antiage"],"skinType":["normal","dry"]}'::jsonb || jsonb_build_object('oldPrice', round(880 * 1.8 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-PT-03');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-CL-01', 'Антицеллюлитный гель-крем', 'Body Flow', 'Уход для тела', 990, 'Разогревающий гель для проблемных зон.', 'Кофеин, перец', 'Антицеллюлитный уход', true, '/demo/photos/20h-C0vaNBA.jpg', '{"productType":"Антицеллюлитный гель","volume":"200 мл","tags":["body-anticellulite"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(990 * 1.7 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-CL-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-CL-02', 'Антицеллюлитное масло для массажа', 'Body Flow', 'Уход для тела', 1190, 'Масло для массажа бёдер и ягодиц.', 'Масло грейпфрута, розмарин', 'Антицеллюлитный уход', true, '/demo/photos/pd4rqJMd51Q.jpg', '{"productType":"Масло для тела","volume":"150 мл","tags":["body-anticellulite","body-oil"]}'::jsonb || jsonb_build_object('oldPrice', round(1190 * 1.6 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-CL-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-FT-01', 'Крем для ног смягчающий', 'Silk Lab', 'Уход для тела', 460, 'Смягчает пятки и снимает усталость.', 'Мочевина 10%, мята', 'Сухая кожа ног', true, '/demo/photos/XanILp6v_Eg.jpg', '{"productType":"Крем для ног","volume":"100 мл","tags":["body-feet"]}'::jsonb || jsonb_build_object('oldPrice', round(460 * 1.5 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-FT-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-FT-02', 'Пилинг-носочки для ног', 'Seoul Skin', 'Уход для тела', 690, 'Домашний педикюр за 60 минут.', 'Кислоты, 1 пара', 'Огрубевшая кожа стоп', true, '/demo/photos/2bQ82FvUAFg.jpg', '{"productType":"Пилинг для ног","volume":"1 пара","tags":["body-feet","body-scrub"],"hit":true}'::jsonb || jsonb_build_object('oldPrice', round(690 * 1.8 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-FT-02');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-HN-01', 'Крем для рук с гиалуроновой кислотой', 'Glow Co', 'Уход для тела', 380, 'Увлажняющий крем, быстро впитывается.', 'Гиалуроновая кислота, 75 мл', 'Сухая кожа рук', true, '/demo/photos/XanILp6v_Eg.jpg', '{"productType":"Крем для рук","volume":"75 мл","tags":["body-hands"]}'::jsonb || jsonb_build_object('oldPrice', round(380 * 1.5 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-HN-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-BC-01', 'Молочко для тела питательное', 'Silk Lab', 'Уход для тела', 640, 'Питание и мягкость на весь день.', 'Масло ши, витамин E', 'Сухая кожа тела', true, '/demo/photos/20h-C0vaNBA.jpg', '{"productType":"Молочко для тела","volume":"300 мл","tags":["body-cream"]}'::jsonb || jsonb_build_object('oldPrice', round(640 * 1.6 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-BC-01');
insert into products (store_id, sku, name, brand, category, price, description, characteristics, purpose, in_stock, image_url, attributes)
select (select store_id from profiles where role = 'owner' limit 1), 'DEMO-SS-01', 'Солнцезащитный стик SPF 50', 'Sun Guard', 'SPF', 890, 'Удобный стик для лица и зоны вокруг глаз.', 'SPF 50, PA++++', 'Защита в течение дня', true, '/demo/photos/UYJTgxZtUmk.jpg', '{"productType":"Солнцезащитный стик","volume":"18 г","tags":["spf-face","spf-stick"],"skinType":["dry","oily","combination","normal","sensitive"]}'::jsonb || jsonb_build_object('oldPrice', round(890 * 1.6 / 10) * 10)
where not exists (select 1 from products where sku = 'DEMO-SS-01');
