// Single source of truth for the catalog structure (Каталог → Основная категория → Подкатегория → Товары).
// `node scripts/build-catalog.mjs` turns it into:
//   src/lib/catalog-structure.json   — the tiles / sub-category lists the app renders
//   supabase/catalog_structure.sql   — ADDITIVE demo data: tags for existing demo products +
//                                      new demo products so no sub-category is empty.
// Product tuple: [name, brand, price, volume]

const ALL = ["dry", "oily", "combination", "normal", "sensitive"];

// Photo pools (files in public/demo/photos/<id>.jpg — see scripts/fetch-demo-photos.mjs)
export const POOLS = {
  cream: ["UYJTgxZtUmk", "lpFTFW9BZSU", "omY18KP7_Cw"],
  serum: ["9PnU-U7V6YE", "pd4rqJMd51Q", "LeWrouH2qto"],
  clean: ["20h-C0vaNBA", "nl3uvcm1w5M", "YwgaLtnYX4k"],
  mask: ["2bQ82FvUAFg", "DNohKoNoKEk", "omY18KP7_Cw"],
  tube: ["UYJTgxZtUmk", "XanILp6v_Eg", "lpFTFW9BZSU"],
  pump: ["nl3uvcm1w5M", "20h-C0vaNBA", "Ui7QkgvUBZ0"],
  shampoo: ["YwgaLtnYX4k", "Ui7QkgvUBZ0", "m3rBOi881fo"],
  jar: ["omY18KP7_Cw", "2bQ82FvUAFg", "DNohKoNoKEk"],
  spray: ["pODoOEsYr_I", "20h-C0vaNBA", "nl3uvcm1w5M"],
  lips: ["NnsqpLjiA94", "mSHRwz_FlLY", "xwM61TPMlYk"],
  eyes: ["5Us84s7blq8", "l3fh8RDxCvA", "PZ_-sCaBCaQ"],
  face: ["20h-C0vaNBA", "A_ZiNBM1J5c", "P_gQpl-a_R4"],
  brushes: ["9QSXCwqc-u4", "LI_lEhTifRg", "yd3mg93Smn8", "BkaD07QEiJc"],
  nails: ["FqpSyjCdccw", "MUVKrHNMvoQ", "S6crviGv5wY"],
  perfume: ["W_mMinc50k8", "49c-5-bNCRk", "W_mMinc50k8"],
  lingerie: ["Z00Dhp_tk38", "AdjyrNhFVPI", "Z00Dhp_tk38"],
  soap: ["cxAZxTuL7Sk", "QeIUZMA2mdU", "nl3uvcm1w5M"],
  deo: ["FXCsQsSer1c", "pODoOEsYr_I", "XanILp6v_Eg"],
  shave: ["CbyN1eWQyS8", "FXCsQsSer1c", "CbyN1eWQyS8"],
  home: ["2QSsfflO51I", "n8BjsYWTH8w", "7JxP1pYYIUo"],
  gift: ["ZLTlHeKbh04", "f94JPVrDbnY", "I7C5S7868Jk", "rO20Sn1FWo4"],
  merch: ["TeD4qZjGIMw", "AJsdrXaRhHk", "g5GXUqF_QDI"],
  kids: ["ED3F5UhUv5s", "lpFTFW9BZSU", "Ui7QkgvUBZ0"],
  acc: ["b_wK7JiEny8", "rO20Sn1FWo4", "I7C5S7868Jk"],
  massage: ["mSHRwz_FlLY", "xwM61TPMlYk", "5Us84s7blq8"],
};

// Sub-category: { label, tag, pool, blurb, chars, purpose, skin?, hair?, cat?, items: [[name, brand, price, volume]] }
// `attr` sub-categories (hair type) reuse products of other subs and need no items of their own.
export const GROUPS = [
  {
    name: "Уход за лицом", icon: "Smile", cat: "Уход за лицом", skin: ALL,
    categories: ["Уход за лицом", "Очищение", "Тоники", "Сыворотки", "Кремы", "Маски", "Уход за глазами", "SPF", "Массажеры"],
    subs: [
      { label: "Очищение и умывание", tag: "cleansing", items: [] },
      { label: "Снятие макияжа", tag: "makeup-removal", cat: "Очищение", pool: "clean", blurb: "Бережно растворяет макияж и SPF.", chars: "Без отдушек", purpose: "Все типы кожи",
        items: [["Гидрофильное масло для снятия макияжа", "Dermalux", 890, "150 мл"], ["Бальзам-щербет для снятия макияжа", "Seoul Skin", 950, "100 мл"]] },
      { label: "Тонеры и лосьоны", tag: "toner", items: [] },
      { label: "Сыворотки", tag: "serum", items: [] },
      { label: "Кремы", tag: "cream", items: [] },
      { label: "Маски", tag: "mask", cat: "Маски", pool: "mask", blurb: "Интенсивный уход за 15 минут.", chars: "Без парабенов", purpose: "Все типы кожи",
        items: [["Альгинатная маска с гиалуроновой кислотой", "Dermalux", 690, "100 г"]] },
      { label: "Скрабы и пилинги", tag: "scrub", pool: "jar", blurb: "Мягко обновляет кожу.", chars: "Без микропластика", purpose: "Тусклая кожа",
        items: [["Энзимная пудра для умывания", "Seoul Skin", 760, "60 г"]] },
      { label: "Пэды", tag: "pad", pool: "mask", blurb: "Пропитанные пэды для быстрого ухода.", chars: "Без спирта", purpose: "Все типы кожи",
        items: [["Пэды с ниацинамидом, 50 шт", "Dermalux", 1090, "50 шт"]] },
      { label: "Патчи", tag: "patch", items: [] },
      { label: "Для кожи вокруг глаз", tag: "eye", items: [] },
      { label: "Для губ", tag: "lips", pool: "lips", blurb: "Питание и защита губ.", chars: "Без отдушек", purpose: "Сухие губы",
        items: [["Скраб для губ «Сахар»", "Silk Lab", 380, "15 г"]] },
      { label: "Средства от акне", tag: "problem", items: [] },
      { label: "Антивозрастной уход", tag: "antiage", items: [] },
      { label: "Средства с ПДРН", tag: "pdrn", cat: "Сыворотки", pool: "serum", blurb: "Восстановление и регенерация кожи.", chars: "ПДРН", purpose: "Уставшая кожа",
        items: [["Крем с ПДРН и коллагеном", "Seoul Skin", 1790, "50 мл"]] },
      { label: "Средства с микроиглами", tag: "microneedle", cat: "Сыворотки", pool: "serum", blurb: "Микроиглы для глубокого воздействия.", chars: "Гиалуроновая кислота", purpose: "Зрелая кожа",
        items: [["Микроигольная сыворотка «Shot»", "Seoul Skin", 1490, "30 мл"]] },
      { label: "SPF-защита", tag: "spf-face", items: [] },
      { label: "Массажёры для лица", tag: "massage-face", cat: "Массажеры", pool: "massage", blurb: "Массаж для лимфодренажа и лифтинга.", chars: "Натуральный камень", purpose: "Массаж лица", skin: [],
        items: [["Электрический массажёр для лица EMS", "Jade Touch", 2490, ""]] },
    ],
  },
  {
    name: "Уход за телом", icon: "PersonStanding", cat: "Уход для тела", skin: [],
    categories: ["Уход для тела", "SPF", "Массажеры"],
    subs: [
      { label: "Гели для душа", tag: "body-shower", pool: "pump", blurb: "Мягкое очищение и приятный аромат.", chars: "Без сульфатов", purpose: "Ежедневный уход",
        items: [["Гель для душа «Кокос и ваниль»", "Silk Lab", 450, "400 мл"], ["Гель для душа «Морской бриз»", "Body Flow", 420, "400 мл"], ["Гель-масло для душа «Миндаль»", "Glow Co", 620, "250 мл"]] },
      { label: "Скрабы и пилинги", tag: "body-scrub", pool: "jar", blurb: "Отшелушивает и выравнивает кожу тела.", chars: "Натуральные абразивы", purpose: "Все типы кожи",
        items: [["Сахарный скраб для тела «Апельсин»", "Silk Lab", 580, "250 г"]] },
      { label: "Кремы для тела", tag: "body-cream", pool: "cream", blurb: "Питательный крем на целый день.", chars: "Масло ши", purpose: "Сухая кожа тела",
        items: [["Питательный крем для тела «Ши»", "Silk Lab", 720, "250 мл"], ["Крем-баттер для тела «Какао»", "Glow Co", 790, "200 мл"], ["Лёгкий крем для тела с алоэ", "Body Flow", 560, "250 мл"]] },
      { label: "Лосьоны и молочко", tag: "body-lotion", pool: "pump", blurb: "Быстро впитывается, не оставляет плёнки.", chars: "Глицерин", purpose: "Ежедневный уход",
        items: [["Лосьон для тела с гиалуроновой кислотой", "Glow Co", 690, "300 мл"]] },
      { label: "Масла для тела", tag: "body-oil", pool: "serum", blurb: "Питание и сияние кожи.", chars: "Натуральные масла", purpose: "Тусклая кожа",
        items: [["Сухое масло для тела с шиммером", "Glow Co", 890, "100 мл"]] },
      { label: "Дезодоранты", tag: "deodorant", pool: "deo", blurb: "Защита от запаха на 48 часов.", chars: "Без спирта", purpose: "Ежедневная защита",
        items: [["Дезодорант-стик «Свежесть»", "Body Flow", 380, "50 г"], ["Роликовый антиперспирант «Sensitive»", "Body Flow", 420, "50 мл"], ["Кристаллический дезодорант", "Silk Lab", 460, "60 г"]] },
      { label: "Для рук", tag: "body-hands", pool: "tube", blurb: "Защита и увлажнение кожи рук.", chars: "Пантенол", purpose: "Сухая кожа рук",
        items: [["Крем для рук «Ши и мёд»", "Silk Lab", 340, "75 мл"], ["Маска-перчатки для рук", "Seoul Skin", 520, "1 пара"]] },
      { label: "Для ног", tag: "body-feet", pool: "tube", blurb: "Смягчает и освежает кожу стоп.", chars: "Мочевина", purpose: "Сухая кожа ног",
        items: [["Дезодорирующий спрей для ног", "Body Flow", 390, "100 мл"]] },
      { label: "Антицеллюлитный уход", tag: "body-anticellulite", pool: "pump", blurb: "Разогревающий уход для проблемных зон.", chars: "Кофеин", purpose: "Антицеллюлитный уход",
        items: [["Антицеллюлитный скраб-гель", "Body Flow", 780, "200 мл"]] },
      { label: "Защита от солнца", tag: "spf-body", cat: "SPF", pool: "tube", blurb: "Водостойкая защита для тела.", chars: "SPF 50", purpose: "Пляж и отпуск",
        items: [["Солнцезащитное молочко для тела SPF 30", "Sun Guard", 890, "200 мл"], ["Солнцезащитное масло-спрей SPF 15", "Sun Guard", 1050, "150 мл"]] },
      { label: "Массажёры для тела", tag: "massage-body", cat: "Массажеры", pool: "massage", blurb: "Для расслабления мышц и тонуса.", chars: "Перезаряжаемый", purpose: "Массаж тела",
        items: [["Роллер для тела «Валик»", "Body Flow", 1190, ""], ["Скребок для массажа тела", "Jade Touch", 760, ""]] },
    ],
  },
  {
    name: "Уход за волосами", label: "Волосы", icon: "Scissors", cat: "Уход за волосами", skin: [],
    categories: ["Уход за волосами", "Шампуни", "Кондиционеры", "Маски для волос"],
    subs: [
      { label: "Шампуни", tag: "shampoo", items: [] },
      { label: "Кондиционеры и бальзамы", tag: "conditioner", items: [] },
      { label: "Маски", tag: "hair-mask", items: [] },
      { label: "Сыворотки и масла", tag: "hair-care", pool: "serum", blurb: "Несмываемый уход для блеска и защиты.", chars: "Аргановое масло", purpose: "Тип волос: сухие", hair: ["dry", "damaged"],
        items: [["Термозащитная сыворотка для волос", "Hair Lab", 690, "100 мл"]] },
      { label: "Сухие шампуни", tag: "dry-shampoo", pool: "spray", blurb: "Свежесть волос без мытья.", chars: "Рисовый крахмал", purpose: "Тип волос: жирные", hair: ["oily"],
        items: [["Сухой шампунь «Fresh Root»", "Pure Hair", 520, "200 мл"], ["Сухой шампунь для тёмных волос", "Pure Hair", 540, "200 мл"], ["Сухой шампунь-пудра", "Hair Lab", 480, "50 г"]] },
      { label: "Укладка", tag: "styling", pool: "pump", blurb: "Форма и фиксация без утяжеления.", chars: "Не склеивает", purpose: "Тип волос: нормальные", hair: ["normal"],
        items: [["Гель для укладки сильной фиксации", "Hair Lab", 420, "150 мл"], ["Мусс для объёма", "Hair Lab", 460, "200 мл"], ["Воск-паста для текстуры", "Pure Hair", 510, "75 мл"]] },
      { label: "Лаки для волос", tag: "hairspray", pool: "spray", blurb: "Надёжная фиксация на весь день.", chars: "Не склеивает", purpose: "Тип волос: нормальные", hair: ["normal"],
        items: [["Лак для волос сильной фиксации", "Hair Lab", 480, "300 мл"], ["Лак-спрей с блеском", "Pure Hair", 520, "250 мл"], ["Текстурирующий спрей «Морская соль»", "Pure Hair", 560, "200 мл"]] },
      { label: "Окрашивание", tag: "hair-color", pool: "jar", blurb: "Стойкий цвет и уход за окрашенными волосами.", chars: "С аммиаком/без", purpose: "Тип волос: окрашенные", hair: ["colored"],
        items: [["Крем-краска для волос, тон 7.1", "Color Care", 640, "100 мл"], ["Тонирующий бальзам «Пепельный блонд»", "Color Care", 590, "150 мл"], ["Оттеночный шампунь против жёлтизны", "Color Care", 610, "250 мл"]] },
      { label: "Уход за кожей головы", tag: "scalp", pool: "serum", blurb: "Здоровая кожа головы и рост волос.", chars: "Пироктон оламин", purpose: "Тип волос: жирные", hair: ["oily", "normal"],
        items: [["Пилинг для кожи головы", "Pure Hair", 780, "150 мл"], ["Сыворотка против выпадения", "Hair Lab", 1290, "100 мл"], ["Тоник для кожи головы", "Pure Hair", 690, "100 мл"]] },
      { label: "Сухие волосы", tag: "", attr: { hairType: "dry" }, items: [] },
      { label: "Жирные волосы", tag: "", attr: { hairType: "oily" }, items: [] },
      { label: "Повреждённые волосы", tag: "", attr: { hairType: "damaged" }, items: [] },
      { label: "Окрашенные волосы", tag: "", attr: { hairType: "colored" }, items: [] },
    ],
  },
  {
    name: "Макияж", icon: "Brush", cat: "Макияж", skin: [],
    categories: ["Макияж"],
    subs: [
      { label: "Тональные средства", tag: "foundation", pool: "face", blurb: "Ровный тон и естественное покрытие.", chars: "SPF 15", purpose: "На каждый день",
        items: [["Тональный крем «Silk Skin»", "Velvet", 980, "30 мл"], ["Тональный флюид «Glow»", "Nude Studio", 1120, "30 мл"], ["Тональный кушон «Cloud»", "Lumi", 1350, "15 г"]] },
      { label: "Консилеры", tag: "concealer", pool: "face", blurb: "Маскирует круги и несовершенства.", chars: "Стойкий", purpose: "Коррекция",
        items: [["Жидкий консилер «Bright»", "Velvet", 620, "6 мл"], ["Консилер-карандаш", "Nude Studio", 540, "3 г"], ["Кремовый консилер-палетка", "Lumi", 890, "8 г"]] },
      { label: "Пудры", tag: "powder", pool: "face", blurb: "Матовое покрытие на весь день.", chars: "Микропудра", purpose: "Фиксация макияжа",
        items: [["Рассыпчатая пудра прозрачная", "Velvet", 690, "15 г"], ["Компактная пудра «Matte»", "Nude Studio", 740, "10 г"], ["Запечённая пудра с сиянием", "Lumi", 880, "9 г"]] },
      { label: "Румяна", tag: "blush", pool: "face", blurb: "Свежий румянец и сияние.", chars: "Пигментированные", purpose: "Макияж лица",
        items: [["Румяна кремовые «Peach»", "Velvet", 620, "5 г"], ["Румяна пудровые «Rose»", "Nude Studio", 580, "6 г"], ["Румяна-стик «Blush Up»", "Lumi", 650, "8 г"]] },
      { label: "Бронзеры и скульпторы", tag: "bronzer", pool: "face", blurb: "Контуринг и лёгкий загар.", chars: "Без апельсиновых пятен", purpose: "Контуринг",
        items: [["Бронзер «Sun Kissed»", "Velvet", 720, "10 г"], ["Скульптор-стик для контуринга", "Nude Studio", 690, "9 г"], ["Палетка для контуринга", "Lumi", 980, "12 г"]] },
      { label: "Хайлайтеры", tag: "highlighter", pool: "face", blurb: "Сияние на скулах и бровях.", chars: "Мелкий шиммер", purpose: "Макияж лица",
        items: [["Хайлайтер «Pearl»", "Velvet", 690, "8 г"], ["Жидкий хайлайтер «Glow Drops»", "Lumi", 640, "15 мл"], ["Хайлайтер-стик «Gold»", "Nude Studio", 620, "9 г"]] },
      { label: "Праймеры и фиксаторы", tag: "primer", pool: "face", blurb: "Основа под макияж и фиксация.", chars: "Не забивает поры", purpose: "Стойкость макияжа",
        items: [["Праймер-основа под макияж", "Velvet", 780, "30 мл"], ["Фиксирующий спрей для макияжа", "Nude Studio", 720, "100 мл"], ["Праймер-гель с эффектом сияния", "Lumi", 850, "30 мл"]] },
      { label: "Тушь", tag: "mascara", pool: "eyes", blurb: "Объём и подкручивание ресниц.", chars: "Водостойкая", purpose: "Макияж глаз",
        items: [["Тушь для объёма «Big Eyes»", "Velvet", 640, "10 мл"], ["Тушь для длины «Long Lash»", "Nude Studio", 610, "10 мл"]] },
      { label: "Тени", tag: "eyeshadow", pool: "eyes", blurb: "Выразительный макияж глаз.", chars: "Пигментированные", purpose: "Макияж глаз",
        items: [["Палетка теней «Sunset», 9 цветов", "Lumi", 1190, "9 цветов"], ["Моно-тени «Shimmer»", "Velvet", 380, "2 г"]] },
      { label: "Карандаши и подводки", tag: "eyeliner", pool: "eyes", blurb: "Чёткая линия и стойкий цвет.", chars: "Водостойкие", purpose: "Макияж глаз",
        items: [["Гелевый карандаш для глаз чёрный", "Velvet", 420, "1.2 г"], ["Жидкая подводка-фломастер", "Nude Studio", 480, "1 мл"], ["Каял для внутреннего века", "Lumi", 390, "1.4 г"]] },
      { label: "Брови", tag: "brows", pool: "eyes", blurb: "Форма и цвет бровей.", chars: "Стойкие", purpose: "Макияж бровей",
        items: [["Карандаш для бровей с щёточкой", "Nude Studio", 420, "0.3 г"], ["Гель для фиксации бровей", "Velvet", 460, "6 мл"], ["Помада для бровей", "Lumi", 590, "4 г"]] },
      { label: "Помады", tag: "lipstick", pool: "lips", blurb: "Стойкий цвет и комфорт.", chars: "Не сушит", purpose: "Макияж губ",
        items: [["Помада матовая «Nude»", "Nude Studio", 720, "3.5 г"], ["Помада кремовая «Berry»", "Lumi", 760, "3.5 г"]] },
      { label: "Блески и бальзамы", tag: "lipgloss", pool: "lips", blurb: "Блеск и питание губ.", chars: "Не липнет", purpose: "Макияж губ",
        items: [["Блеск для губ «Crystal»", "Velvet", 480, "6 мл"], ["Тинт-бальзам для губ", "Nude Studio", 520, "4 г"], ["Масло для губ «Cherry»", "Lumi", 540, "6 мл"]] },
      { label: "Лак для ногтей", tag: "nails", pool: "nails", blurb: "Яркий цвет и стойкое покрытие.", chars: "Без формальдегида", purpose: "Маникюр",
        items: [["Лак для ногтей «Cherry»", "Nude Studio", 320, "10 мл"], ["Гель-лак «Milk»", "Lumi", 380, "10 мл"], ["Закрепитель-топ с блеском", "Velvet", 340, "10 мл"]] },
    ],
  },
  {
    name: "Парфюм", icon: "SprayCan", cat: "Парфюм", skin: [],
    categories: ["Парфюм"],
    subs: [
      { label: "Женская парфюмерия", tag: "perfume-women", pool: "perfume", blurb: "Цветочно-фруктовые ароматы.", chars: "Стойкость 6–8 часов", purpose: "Женский аромат",
        items: [["Парфюмерная вода «Velvet Rose»", "Maison Rose", 3400, "50 мл"], ["Парфюмерная вода «Pink Sky»", "Maison Rose", 2900, "30 мл"]] },
      { label: "Мужская парфюмерия", tag: "perfume-men", pool: "perfume", blurb: "Древесные и свежие ароматы.", chars: "Стойкость 6–8 часов", purpose: "Мужской аромат",
        items: [["Туалетная вода «Cedar Wood»", "Maison Rose", 3100, "50 мл"], ["Парфюмерная вода «Night Rider»", "Maison Rose", 3600, "50 мл"], ["Туалетная вода «Aqua Sport»", "Maison Rose", 2600, "100 мл"]] },
      { label: "Унисекс", tag: "perfume-unisex", pool: "perfume", blurb: "Универсальные ароматы.", chars: "Стойкость 5–7 часов", purpose: "Унисекс",
        items: [["Парфюмерная вода «Amber Musk»", "Maison Rose", 3300, "50 мл"], ["Одеколон «Citrus Garden»", "Maison Rose", 2200, "100 мл"]] },
      { label: "Наборы и миниатюры", tag: "perfume-set", pool: "perfume", blurb: "Для знакомства с ароматами.", chars: "3 аромата", purpose: "Подарок или проба",
        items: [["Набор миниатюр «Floral»", "Maison Rose", 1900, "3 × 10 мл"], ["Подарочный набор «Rose + крем»", "Maison Rose", 3700, "50 мл + 75 мл"]] },
      { label: "Мисты для тела и волос", tag: "mist", pool: "spray", blurb: "Лёгкий аромат на каждый день.", chars: "Без спирта", purpose: "Ежедневный аромат",
        items: [["Мист для тела «Vanilla Cloud»", "Glow Co", 650, "150 мл"], ["Мист для волос «Peony»", "Hair Lab", 590, "100 мл"], ["Парфюмированный спрей «Cotton»", "Glow Co", 620, "150 мл"]] },
      { label: "Масляные духи и роллеры", tag: "perfume-roll", pool: "perfume", blurb: "Компактный аромат с собой.", chars: "Роллер", purpose: "Ароматы в сумочку",
        items: [["Масляные духи «Jasmine»", "Maison Rose", 1290, "10 мл"], ["Роллер «Amber»", "Maison Rose", 1190, "10 мл"], ["Твёрдые духи «Wood»", "Maison Rose", 990, "8 г"]] },
    ],
  },
  {
    name: "Аптечная косметика", icon: "FlaskConical", cat: "Аптечная косметика", skin: ["sensitive", "dry"],
    categories: ["Аптечная косметика"],
    subs: [
      { label: "Для чувствительной кожи", tag: "pharm-sensitive", pool: "clean", blurb: "Гипоаллергенный уход.", chars: "Без отдушек", purpose: "Чувствительная кожа",
        items: [["Термальная вода-спрей", "Derma Care", 690, "150 мл"]] },
      { label: "Против акне", tag: "pharm-acne", pool: "tube", blurb: "Лечебный уход за проблемной кожей.", chars: "Цинк", purpose: "Проблемная кожа",
        items: [["Сыворотка против несовершенств", "Derma Care", 1190, "30 мл"], ["Очищающий гель для проблемной кожи", "Derma Care", 890, "200 мл"]] },
      { label: "Восстанавливающие", tag: "pharm-repair", pool: "cream", blurb: "Восстановление барьера кожи.", chars: "Церамиды", purpose: "Раздражённая кожа",
        items: [["Бальзам «Спасатель»", "Derma Care", 780, "40 мл"], ["Крем-барьер с цинком", "Derma Care", 690, "100 мл"]] },
      { label: "Витамины красоты", tag: "pharm-vitamins", pool: "jar", blurb: "Поддержка кожи, волос и ногтей изнутри.", chars: "60 капсул", purpose: "Красота изнутри",
        items: [["Комплекс «Волосы, кожа, ногти»", "Derma Care", 1190, "60 шт"], ["Коллаген с витамином C", "Derma Care", 1690, "30 саше"], ["Омега-3 для кожи", "Derma Care", 990, "90 капсул"]] },
      { label: "Для проблем с волосами", tag: "pharm-hair", pool: "shampoo", blurb: "Терапевтический уход за волосами.", chars: "Клинически проверено", purpose: "Выпадение и перхоть",
        items: [["Шампунь против перхоти", "Derma Care", 790, "200 мл"], ["Лосьон против выпадения", "Derma Care", 1390, "100 мл"], ["Ампулы для роста волос", "Derma Care", 1590, "10 × 10 мл"]] },
    ],
  },
  {
    name: "Личная гигиена", icon: "ShieldCheck", cat: "Личная гигиена", skin: [],
    categories: ["Личная гигиена"],
    subs: [
      { label: "Прокладки и тампоны", tag: "hyg-pads", pool: "soap", blurb: "Комфорт в критические дни.", chars: "Дышащие", purpose: "Критические дни",
        items: [["Прокладки ночные, 12 шт", "Soft Day", 290, "12 шт"]] },
      { label: "Интимная гигиена", tag: "hyg-intimate", pool: "pump", blurb: "Мягкий уход с нейтральным pH.", chars: "pH 4.5", purpose: "Ежедневный уход",
        items: [["Салфетки для интимной гигиены", "Soft Day", 260, "20 шт"], ["Пенка для интимной гигиены", "Soft Day", 520, "150 мл"]] },
      { label: "Уход за полостью рта", tag: "hyg-oral", pool: "kids", blurb: "Здоровье зубов и свежее дыхание.", chars: "С фтором", purpose: "Ежедневный уход",
        items: [["Зубная паста отбеливающая", "Pure Wash", 320, "100 мл"], ["Зубная щётка мягкая", "Pure Wash", 180, "1 шт"], ["Ополаскиватель для рта", "Pure Wash", 350, "250 мл"]] },
      { label: "Бритьё", tag: "hyg-shaving", pool: "shave", blurb: "Гладкое бритьё без раздражения.", chars: "Без спирта", purpose: "Бритьё",
        items: [["Бритвенный станок женский", "Soft Day", 420, "1 шт"], ["Пена для бритья", "Soft Day", 360, "200 мл"], ["Лосьон после бритья", "Soft Day", 390, "100 мл"]] },
      { label: "Депиляция", tag: "hyg-depil", pool: "jar", blurb: "Гладкая кожа надолго.", chars: "Сахарная паста", purpose: "Депиляция",
        items: [["Сахарная паста для шугаринга", "Soft Day", 690, "300 г"], ["Полоски для депиляции, 20 шт", "Soft Day", 420, "20 шт"], ["Крем для депиляции", "Soft Day", 450, "100 мл"]] },
    ],
  },
  {
    name: "Нижнее бельё", icon: "Heart", cat: "Нижнее бельё", skin: [],
    categories: ["Нижнее бельё"],
    subs: [
      { label: "Комплекты белья", tag: "uw-sets", pool: "lingerie", blurb: "Бюстгальтер и трусики в одном стиле.", chars: "Мягкое кружево", purpose: "Комплект",
        items: [["Комплект «Кружево»", "Lace & Co", 2190, ""], ["Комплект «Хлопок»", "Lace & Co", 1590, ""]] },
      { label: "Бюстгальтеры", tag: "uw-bras", pool: "lingerie", blurb: "Комфорт и поддержка.", chars: "Без косточек", purpose: "Повседневный",
        items: [["Бюстгальтер с косточками «Classic»", "Lace & Co", 1490, ""], ["Бралетт «Soft»", "Lace & Co", 990, ""]] },
      { label: "Трусики", tag: "uw-briefs", pool: "lingerie", blurb: "Комфортное бельё на каждый день.", chars: "Хлопок", purpose: "Повседневные",
        items: [["Трусики-бразилиана", "Lace & Co", 490, ""], ["Трусики-слипы, набор 3 шт", "Lace & Co", 890, "3 шт"]] },
      { label: "Домашняя одежда", tag: "uw-sleep", pool: "lingerie", blurb: "Мягкая одежда для дома и сна.", chars: "Вискоза", purpose: "Дом и сон",
        items: [["Пижама «Шёлк»", "Lace & Co", 2490, ""], ["Халат махровый", "Lace & Co", 2190, ""], ["Сорочка «Нежность»", "Lace & Co", 1490, ""]] },
      { label: "Носки и колготки", tag: "uw-hosiery", pool: "lingerie", blurb: "Комфорт и стиль на каждый день.", chars: "Эластичные", purpose: "Повседневные",
        items: [["Колготки 40 den", "Lace & Co", 390, ""], ["Носки хлопковые, набор 5 пар", "Lace & Co", 420, "5 пар"], ["Чулки с кружевом", "Lace & Co", 690, ""]] },
      { label: "Купальники", tag: "uw-swim", pool: "lingerie", blurb: "Для пляжа и бассейна.", chars: "Быстросохнущие", purpose: "Пляж",
        items: [["Купальник слитный «Wave»", "Lace & Co", 2390, ""], ["Раздельный купальник «Coral»", "Lace & Co", 2190, ""], ["Парео пляжное", "Lace & Co", 1190, ""]] },
    ],
  },
  {
    name: "Мыломоющие средства", icon: "Droplets", cat: "Мыломоющие средства", skin: [],
    categories: ["Мыломоющие средства"],
    subs: [
      { label: "Жидкое мыло", tag: "soap-liquid", pool: "pump", blurb: "Мягко очищает руки.", chars: "Без сульфатов", purpose: "Ежедневное",
        items: [["Жидкое мыло «Цитрус»", "Pure Wash", 240, "500 мл"], ["Жидкое мыло «Алоэ»", "Pure Wash", 250, "500 мл"]] },
      { label: "Гели для душа", tag: "soap-shower", pool: "pump", blurb: "Освежающее очищение.", chars: "pH-баланс", purpose: "Ежедневное",
        items: [["Гель для душа «Мята»", "Pure Wash", 380, "400 мл"], ["Гель для душа «Лаванда»", "Pure Wash", 390, "400 мл"]] },
      { label: "Твёрдое мыло", tag: "soap-bar", pool: "soap", blurb: "Натуральное мыло ручной работы.", chars: "Натуральный состав", purpose: "Ручной уход",
        items: [["Мыло «Лаванда и мёд»", "Pure Wash", 220, "100 г"], ["Мыло «Апельсин»", "Pure Wash", 210, "100 г"]] },
      { label: "Пена и соли для ванны", tag: "soap-bath", pool: "soap", blurb: "Расслабляющая ванна.", chars: "Морская соль", purpose: "Релакс",
        items: [["Соль для ванны «Лаванда»", "Pure Wash", 380, "500 г"], ["Пена для ванны «Ваниль»", "Pure Wash", 420, "500 мл"], ["Бомбочка для ванны", "Pure Wash", 190, "120 г"]] },
    ],
  },
  {
    name: "Для дома", icon: "House", cat: "Для дома", skin: [],
    categories: ["Для дома"],
    subs: [
      { label: "Свечи", tag: "home-candles", pool: "home", blurb: "Аромат и уют в доме.", chars: "Соевый воск", purpose: "Уют и подарок",
        items: [["Ароматическая свеча «Сандал»", "Cozy", 790, "200 г"], ["Свеча «Морской бриз»", "Cozy", 760, "200 г"]] },
      { label: "Диффузоры", tag: "home-diffusers", pool: "home", blurb: "Постоянный аромат в комнате.", chars: "С палочками", purpose: "Ароматизация дома",
        items: [["Диффузор «Белый чай»", "Cozy", 1190, "100 мл"], ["Диффузор «Лимонная трава»", "Cozy", 1150, "100 мл"]] },
      { label: "Спреи для дома и текстиля", tag: "home-textile", pool: "spray", blurb: "Освежает воздух и ткани.", chars: "Без спирта", purpose: "Свежесть в доме",
        items: [["Спрей для подушек «Лаванда»", "Cozy", 520, "150 мл"], ["Освежитель воздуха «Хлопок»", "Cozy", 460, "250 мл"]] },
      { label: "Декор и аксессуары", tag: "home-decor", pool: "home", blurb: "Мелочи для уюта.", chars: "Натуральные материалы", purpose: "Декор",
        items: [["Подставка для свечи", "Cozy", 390, ""], ["Аромасаше «Лаванда»", "Cozy", 290, ""], ["Набор спичек в банке", "Cozy", 260, ""]] },
    ],
  },
  {
    name: "Для детей", icon: "Baby", cat: "Для детей", skin: [],
    categories: ["Для детей"],
    subs: [
      { label: "Уход за малышом", tag: "kids-care", pool: "cream", blurb: "Нежный уход с рождения.", chars: "Гипоаллергенно", purpose: "С рождения",
        items: [["Детское молочко для тела", "Little Bloom", 420, "250 мл"], ["Детское масло для массажа", "Little Bloom", 460, "150 мл"]] },
      { label: "Купание и шампуни", tag: "kids-wash", pool: "shampoo", blurb: "Мягкое купание без слёз.", chars: "Без слёз", purpose: "С рождения",
        items: [["Детский гель для купания", "Little Bloom", 380, "400 мл"], ["Детская пена для ванны", "Little Bloom", 350, "300 мл"]] },
      { label: "Гигиена полости рта", tag: "kids-oral", pool: "kids", blurb: "Первые зубки под защитой.", chars: "Без фтора", purpose: "От 1 года",
        items: [["Детская зубная щётка мягкая", "Little Bloom", 190, "1 шт"], ["Гель для дёсен при прорезывании", "Little Bloom", 350, "15 мл"]] },
      { label: "Подгузники и салфетки", tag: "kids-diapers", pool: "cream", blurb: "Сухо и комфортно.", chars: "Гипоаллергенные", purpose: "С рождения",
        items: [["Подгузники размер 3, 50 шт", "Little Bloom", 1290, "50 шт"], ["Детские влажные салфетки, 72 шт", "Little Bloom", 260, "72 шт"], ["Трусики-подгузники размер 4", "Little Bloom", 1390, "44 шт"]] },
      { label: "Игрушки и аксессуары", tag: "kids-toys", pool: "kids", blurb: "Безопасные игрушки для малышей.", chars: "Натуральное дерево", purpose: "От 6 месяцев",
        items: [["Погремушка деревянная", "Little Bloom", 350, ""], ["Прорезыватель силиконовый", "Little Bloom", 290, ""], ["Кубики мягкие, 6 шт", "Little Bloom", 590, "6 шт"]] },
    ],
  },
  {
    name: "Аксессуары", icon: "Gem", cat: "Аксессуары", skin: [],
    categories: ["Аксессуары"],
    subs: [
      { label: "Расчёски и щётки", tag: "acc-brushes", pool: "acc", blurb: "Бережное расчёсывание.", chars: "Не электризует", purpose: "Ежедневное",
        items: [["Щётка-расчёска «Wet Brush»", "Style Kit", 490, ""], ["Гребень деревянный", "Style Kit", 320, ""]] },
      { label: "Резинки и заколки", tag: "acc-hair", pool: "acc", blurb: "Не портят волосы.", chars: "Мягкие", purpose: "Ежедневное",
        items: [["Заколки-крабы, 3 шт", "Style Kit", 280, "3 шт"], ["Ободок для умывания", "Style Kit", 320, ""]] },
      { label: "Косметички", tag: "acc-bags", pool: "acc", blurb: "Удобное хранение косметики.", chars: "Водоотталкивающие", purpose: "Хранение",
        items: [["Косметичка-органайзер", "Style Kit", 990, ""], ["Дорожная косметичка", "Style Kit", 690, ""]] },
      { label: "Кисти и спонжи", tag: "acc-tools", pool: "brushes", blurb: "Инструменты для макияжа.", chars: "Синтетический ворс", purpose: "Макияж",
        items: [["Набор кистей для макияжа, 12 шт", "Style Kit", 1590, "12 шт"], ["Спонж для тона", "Style Kit", 260, ""], ["Кисть для румян", "Style Kit", 390, ""]] },
      { label: "Зеркала", tag: "acc-mirrors", pool: "acc", blurb: "Компактные зеркала.", chars: "Увеличение x5", purpose: "Макияж",
        items: [["Зеркало карманное", "Style Kit", 290, ""], ["Зеркало с подсветкой", "Style Kit", 1290, ""], ["Зеркало настольное", "Style Kit", 690, ""]] },
    ],
  },
  {
    name: "Мерч", icon: "Shirt", cat: "Мерч", skin: [],
    categories: ["Мерч"],
    subs: [
      { label: "Сумки и шопперы", tag: "merch-bags", pool: "merch", blurb: "Фирменные сумки.", chars: "Плотный хлопок", purpose: "Фирменный мерч",
        items: [["Шоппер «Beauty Pink»", "Merch", 490, ""], ["Косметичка-клатч с логотипом", "Merch", 590, ""]] },
      { label: "Одежда", tag: "merch-clothing", pool: "merch", blurb: "Мягкая фирменная одежда.", chars: "Хлопок 80%", purpose: "Фирменный мерч",
        items: [["Футболка оверсайз", "Merch", 1490, ""], ["Свитшот «Beauty»", "Merch", 2490, ""]] },
      { label: "Кружки и бутылки", tag: "merch-mugs", pool: "merch", blurb: "Для дома и работы.", chars: "Керамика", purpose: "Фирменный мерч",
        items: [["Кружка «Pink»", "Merch", 420, "350 мл"], ["Термобутылка", "Merch", 990, "500 мл"]] },
      { label: "Канцелярия и стикеры", tag: "merch-stationery", pool: "merch", blurb: "Приятные мелочи.", chars: "Бумага 120 г", purpose: "Фирменный мерч",
        items: [["Блокнот «Beauty»", "Merch", 290, ""], ["Набор стикеров", "Merch", 150, ""], ["Ручка розовая", "Merch", 120, ""]] },
    ],
  },
  {
    name: "Подарки", icon: "Gift", cat: "Подарки", skin: [],
    categories: ["Подарки"],
    subs: [
      { label: "Подарочные наборы", tag: "gift-sets", pool: "gift", blurb: "Готовый подарок в красивой коробке.", chars: "Подарочная упаковка", purpose: "Подарок",
        items: [["Набор «Расслабление»", "Gift Box", 2290, "4 продукта"]] },
      { label: "Подарочные сертификаты", tag: "gift-cards", pool: "gift", blurb: "Сертификат на любую сумму.", chars: "Электронный", purpose: "Подарок",
        items: [["Сертификат 1000", "Gift Box", 1000, ""], ["Сертификат 3000", "Gift Box", 3000, ""]] },
      { label: "Упаковка", tag: "gift-wrap", pool: "gift", blurb: "Оформление подарка.", chars: "Плотная бумага", purpose: "Упаковка",
        items: [["Подарочная коробка розовая", "Gift Box", 390, ""], ["Крафт-пакет с лентой", "Gift Box", 190, ""], ["Набор для упаковки подарка", "Gift Box", 490, ""]] },
      { label: "Наборы для лица", tag: "gift-face", pool: "gift", blurb: "Подарок для ухода за лицом.", chars: "3 продукта", purpose: "Подарок",
        items: [["Набор «Сияние»", "Gift Box", 2790, "3 продукта"], ["Набор «Увлажнение»", "Gift Box", 2490, "3 продукта"], ["Мини-набор «Открытие»", "Gift Box", 1490, "4 миниатюры"]] },
    ],
  },
];

// Tags for the demo products that already exist in the database (sku without DEMO-).
export const RETAG = {
  "FF-01": ["cleansing"], "FF-02": ["cleansing", "makeup-removal"], "FF-03": ["cleansing"],
  "FC-01": ["cream"], "FC-02": ["cream", "antiage"], "FC-03": ["cream", "problem"], "FC-04": ["body-hands"],
  "FS-01": ["serum", "antiage"], "FS-02": ["serum"], "FS-03": ["serum", "problem"], "FS-04": ["serum", "antiage"],
  "FM-01": ["mask"], "FM-02": ["mask", "problem"],
  "SP-01": ["spf-face"], "SP-02": ["spf-face"], "SS-01": ["spf-face"], "SP-03": ["spf-body"],
  "MN-01": ["microneedle", "antiage"], "MN-02": ["microneedle", "problem"],
  "PD-01": ["pdrn", "serum", "antiage"], "PD-02": ["pdrn", "serum"],
  "TN-01": ["toner"], "TN-02": ["toner", "problem"], "TN-03": ["toner"],
  "SC-01": ["scrub"], "SC-02": ["scrub"], "PA-01": ["pad"], "PA-02": ["pad"],
  "EY-01": ["eye", "antiage"], "EY-02": ["eye"], "LP-01": ["lips"], "LP-02": ["lips"],
  "PT-01": ["patch", "eye"], "PT-02": ["patch", "problem"], "PT-03": ["patch", "antiage"],
  "MS-01": ["massage-face"], "MS-02": ["massage-face"], "MS-03": ["massage-body"],
  "BD-01": ["body-lotion"], "BC-01": ["body-lotion"], "BD-02": ["body-scrub"], "FT-02": ["body-feet", "body-scrub"],
  "BD-03": ["body-oil"], "CL-02": ["body-oil", "body-anticellulite"], "CL-01": ["body-anticellulite"],
  "HN-01": ["body-hands"], "FT-01": ["body-feet"],
  "HS-01": ["shampoo"], "HS-02": ["shampoo"], "HS-03": ["shampoo"], "HS-04": ["shampoo"],
  "HC-01": ["conditioner"], "HC-02": ["conditioner"], "HC-03": ["conditioner"],
  "HR-02": ["hair-mask"], "HK-01": ["hair-mask"], "HK-02": ["hair-mask"], "HK-03": ["hair-mask"],
  "HR-03": ["hair-care"], "HR-04": ["hair-care"],
  "MK-01": ["lipstick"], "MK-02": ["mascara"], "MK-03": ["eyeshadow"],
  "PF-01": ["perfume-women"], "PF-02": ["perfume-unisex"], "PF-03": ["perfume-set"],
  "AP-01": ["pharm-sensitive"], "AP-02": ["pharm-sensitive", "pharm-repair"], "AP-03": ["pharm-acne"],
  "GG-01": ["hyg-pads"], "GG-02": ["hyg-intimate"], "GG-03": ["hyg-pads"],
  "UW-01": ["uw-sets"], "UW-02": ["uw-briefs"], "UW-03": ["uw-bras"],
  "SO-01": ["soap-liquid"], "SO-02": ["soap-shower"], "SO-03": ["soap-bar"],
  "HM-01": ["home-candles"], "HM-02": ["home-diffusers"], "HM-03": ["home-textile"],
  "KD-01": ["kids-wash"], "KD-02": ["kids-care"], "KD-03": ["kids-oral"],
  "AC-01": ["acc-brushes"], "AC-02": ["acc-hair"], "AC-03": ["acc-bags"],
  "MR-01": ["merch-bags"], "MR-02": ["merch-clothing"], "MR-03": ["merch-mugs"],
  "GF-01": ["gift-sets"], "GF-02": ["gift-sets"], "GF-03": ["gift-cards"],
};
